import = ["/Users/isaacgrannis/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[cursor.style]
blinking = "Off"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font.bold]
family = "Hurmit Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hurmit Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hurmit Nerd Font"
style = "Italic"

[font.normal]
family = "Hurmit Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/etc/profiles/per-user/isaacgrannis/bin/zsh"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Terminal"
